name: pangu
description: Paranoid text spacing for good readability, to automatically insert whitespace between CJK (Chinese, Japanese, Korean), half-width English, digit and symbol characters.
version: 1.1.0
author: Edison Huang <gn00742754@gmail.com>
homepage: https://github.com/SemonCat/pangu.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.2.0
